#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#compton –config /home/localhost/.config/compton/.compton.conf -b &
feh --bg-scale ~/Pictures/wallpapers/grey.png &
~/.scripts/kbmap.sh &
picom &
"$HOME/.config/polybar/launch.sh"
dunst &

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

xinput set-prop 13 'libinput Natural Scrolling Enabled' 1 &
xinput set-prop 12 'libinput Natural Scrolling Enabled' 1 &

bspc config border_width         2
bspc config window_gap          12

bspc config top_padding 	 10 
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Firefox desktop='^1' follow=on focus=on
bspc rule -a Zathura state=tiled
bspc rule -a KeePassXC state=floating center=true focus=on rectangle=1000x700
ngle=1100x780+0+0
bspc rule -a Thunar state=floating center=true
bspc rule -a "MEGAsync" state=floating center=true follow=on
bspc rule -a "Yad" state=floating

# panel &
